### ISSUE TITLE
spike: find a new design for this page on a design site

### ISSUE THREAD

**Issue by techieeliot** [techieeliot/git-example-fcc#5]
@gusmontoya @LodenH16 accept my invitation to this repo. 

Whoever has bandwidth could you do some research (spike) to find a mock-up for us to create documentation for all the commands in git that we learned today.

Assign this to yourself.

Dribbble and Behance are two sites that would have some designs.

As the owner of the repo, I want a very minimalistic design that is black and white with lots of white/black space.

I want a modern look with a modern-looking font.

To close out this ticket paste the link and @ techieeliot in a comment below.

That's it.

**Comment by LodenH16** [comment]
[I think this fits what you are describing well](https://dribbble.com/shots/14977712-WICKEDTEMPLATES-3Rd-REDESIGN-DARK-DOCUMENTATION) @techieeliot

**Comment by techieeliot** [comment]
Perfect 👍 @LodenH16 

Closing issue.

**Comment by techieeliot** [comment]
@LodenH16 Create a new issue for scaffolding out the index.html sections using comments and semantic html elements.
