### ISSUE TITLE
feat: add structure to the html

### ISSUE THREAD

**Issue by LodenH16** [techieeliot/git-example-fcc#6]
Create an html layout following the structure of the design provided in #5

**Comment by LodenH16** [comment]
@techieeliot what do you think about making a Node/Express api that could return all the Git commands and descriptions that are on the cheat sheet you shared with us? I know it's beyond the scope of this exercise but I think it would be a good project.

**Comment by techieeliot** [comment]
Just keep it simple .

Init
Branch
Add .
Commit -m
Push -u
Push
Fetch
Pull
Clone

Optional cmd line
Pwd
Cd ..
Cd folder/
Ls 
Mkdir 
Touch 
Rm
Rm -rf 

Vs code cmd
Code

As you learn more, then add it.

It’s git practice.

**Comment by techieeliot** [comment]
Focus this pr on just the basic scaffolding structure. Create new issues for other chunks and features.
